GET http://localhost:3100/api/tasks

###
GET http://localhost:3100/api/tasks/2

###
POST http://localhost:3100/api/tasks
Content-Type: application/json

{
	"task": "Nueva tarea 03",
	"done": 0
}

###
PUT http://localhost:3100/api/tasks/3
Content-Type: application/json

{
	"task": "Nueva tarea 03",
	"done": 0
}

###
DELETE http://localhost:3100/api/tasks/3

